name: Resource Build

on:
  push:
    branches:
      - feature/*
      - fix/*
      - main

jobs:
  build:
    name: Resource Build
    runs-on:
      - self-hosted
      - Linux

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.6

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build resource
        run: |
          msbuild /p:Configuration=Release /v:q ../src/Client/IndestructibleObjects.Client.csproj
          cp "..\LICENSE" "..\output\LICENSE"
          cp"..\README.md" "..\output\README.md"
